version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "07:00"
    open-pull-requests-limit: 10
    target-branch: master
    labels: [auto-dependencies]